name: deploy artifacts
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "name of the artifact for deployment"
        type: string
        required: false
        default: dist-files
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: dist