name: deploy artifacts
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "name of the artifact for deployment"
        type: string
        required: false
        default: dist-files
    outputs:
      result:
        description: "name of the js file in artifact"
        value: ${{ jobs.deploy.outputs.deploy-result }}

jobs:
  deploy:
    outputs:
      deploy-result: ${{ steps.deploy.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: list artifacts
        run: ls    
      - name: final step
        id: deploy
        run: |
          find assets/*.js -type f -execdir echo 'result={}' >> $GITHUB_OUTPUT ';'   